### ISSUE TITLE
CSS reset

### ISSUE THREAD

**Issue by qixMan** [qixMan/NoteLike#1]
不同浏览器对标签的默认样式不同，容易引起不同浏览器显示不同效果的问题，通常先主动对标签样式进行初始化，这篇博客主要用于收集这些常用或高效的初始化操作。

```CSS
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, img, ins, kbd, q, s, samp,
small, strike, sub, sup, tt, var,
center,
dl, dt, dd, nav ol, nav ul, nav li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font: inherit;
    vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure,
footer, header, hgroup, menu, nav, section {
    display: block;
}
body {
    line-height: 1;
}
nav ol, nav ul {
    list-style: none;
}
blockquote, q {
    quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
    content: '';
    content: none;
}
table {
    border-collapse: collapse;
    border-spacing: 0;
}

.hidden
{
    display:                none;
}

a
{
    text-decoration:        none;
}

ul.unstyled, ol.unstyled
{
    margin-left:                0;
    padding:                    0 0 0 0;
    list-style:                    none;
}

sup, sub
{
    font-size: smaller;
    height: 0;
    line-height: 1;
    vertical-align: baseline;
    _vertical-align: bottom;
    position: relative;
}

sup
{
    bottom: 1ex;
}

sub
{
    top: .5ex;
}

```
